apiVersion: apps/v1
kind: Deployment
metadata:
 name: project4-deployment
spec: 
 replicas: 2
 selector: 
  matchLabels: 
   app: project4
 template:
  metadata: 
   labels: 
    app: project4
  spec: 
   containers: 
   - name: project4-container
     image: uzairchini/project4-app:latest
     imagePullPolicy: Always
     ports: 
     - containerPort: 8000
